# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('Class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Classification', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('Condition_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Condition', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneName',
            fields=[
                ('GeneName_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GeneName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(max_length=3)),
                ('Patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Condition_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.Patient_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('Sequencer', models.CharField(max_length=100)),
                ('Platform', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Details',
            fields=[
                ('Variant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Variant_cDNA', models.CharField(max_length=100, null=True)),
                ('Variant_Protein', models.CharField(max_length=100, null=True)),
                ('Variant_Genome', models.CharField(max_length=100)),
                ('Class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.Classification')),
                ('GeneName_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.GeneName')),
                ('Platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.Sequencing')),
            ],
        ),
        migrations.AddField(
            model_name='patient_variant',
            name='Variant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vars.Variant_Details'),
        ),
    ]
