# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0003_auto_20170301_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='age',
            field=models.IntegerField(),
        ),
    ]
